name: flutter_app
description: A new Flutter project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^3.1.1
  http: ^1.2.2
  geolocator: ^14.0.2
  image_picker: ^1.0.7
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
